Feature update to sq9
cnescatlab/docker-cat pull request #67
Opened 2023-08-11 10:43 UTC by diegorodriguez31

## Proposed changes

Update new tools on last version compatible with SonarQube LTS 9
Fix some testing bugs

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation Update (if none of the other choices apply)

## Issues closed by changes

- [x] Close #66

## Checklist

- [x] I have read the [CONTRIBUTING](CONTRIBUTING.md) doc
- [x] I agree with the [CODE OF CONDUCT](CODE_OF_CONDUCT.md)
- [x] Lint and unit tests pass locally with my changes
- [x] Codacy validates the quality of the modifications
- [x] GitHub Actions CI workflow passes
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)
- [x] Any dependent changes have been merged and published in downstream modules

2023-08-16 07:56 UTC, louisjdmartin requested changes

2023-08-16 07:56 UTC, louisjdmartin commented on .github/workflows/ci.yml
> -      # Publish test results in the pull request discussion
Pourquoi ne plus afficher les logs dans les commentaires de la PR ?

2023-08-16 07:56 UTC, louisjdmartin commented on Dockerfile
> +LABEL maintainer="CATLab"
```suggestion
LABEL maintainer="CNES CAT Lab"
```

2023-08-16 07:56 UTC, louisjdmartin commented on Dockerfile
>  RUN echo 'deb http://ftp.fr.debian.org/debian/ bullseye main contrib non-free' >> /etc/apt/sources.list \
Pourquoi enlever le numéro de version de GCC ?
Le Warning de Codacy est plutot pertinent si on veux garder une image reproductible

2023-08-22 08:15 UTC, diegorodriguez31 commented on .github/workflows/ci.yml
> -      # Publish test results in the pull request discussion
Ce plugin ne fonctionne plus dans notre cas, c'est la même notion que sur l'image SonarQube. On avait décidé de ne plus l'utiliser, et sans le remplacer.

2023-08-22 10:56 UTC, merged